# 1. Create a 3x3x3 array with random values

In [3]:
import numpy as np
arr= np.random.rand(3,3,3)
print(arr)

[[[0.37430158 0.86132184 0.70612394]
  [0.58003729 0.99514867 0.33878477]
  [0.532618   0.29702449 0.07979743]]

 [[0.66017577 0.82743455 0.55076236]
  [0.54464893 0.42282978 0.86380199]
  [0.6771421  0.63660634 0.37243435]]

 [[0.16970199 0.64136469 0.90009882]
  [0.33506038 0.77392931 0.88741205]
  [0.27436263 0.66515617 0.24234804]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:

arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [7]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[-0.02210194, -0.11637243, -1.26703709, -0.82861562, -1.11179123],
       [-1.10037031,  0.56759854,  1.21516599,  1.44079205, -1.12435666],
       [ 1.27687314, -1.10626854,  0.24281528,  1.1341893 ,  0.5861296 ],
       [ 0.81943781, -0.2460991 , -1.19554305,  0.56783847, -1.13268074],
       [ 1.27728009,  0.877927  , -1.10966287,  1.4227814 , -1.06792907]])

# 5. How to find common values between two arrays

In [8]:

arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([1, 2, 3, 4, 6, 9])

# 8. Create random vector of size 10 and replace the maximum value by 0

In [9]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.37488139, 0.87449763, 0.03127574, 0.28822954, 0.3842065 ,
       0.89368199, 0.50043951, 0.64338446, 0.        , 0.58168266])

# 9. How to print all the values of an array?

In [10]:

arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10. Subtract the mean of each row of a matrix

In [12]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[-0.27921164,  0.09492076,  0.18429089],
       [-0.15629675,  0.13611224,  0.02018452],
       [-0.1049037 ,  0.24376236, -0.13885866]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [13]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([3., 3., 6., 2., 1.])

# 12. How to get the diagonal of a dot product?

In [14]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([45, 60, 12])

# 13. How to find the most frequent value in an array?

In [ ]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

# 14. How to get the n largest values of an array

In [15]:

arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

3

# 15. How to create a record array from a regular array?

In [16]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])

# 6. How to get the dates of yesterday, today and tomorrow?

In [17]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-07-25 2020-07-26 2020-07-27


# 7. Consider two random array A and B, check if they are equa

In [18]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.28790879 0.80540797 0.84454266]
 [0.08196493 0.50669686 0.00971994]
 [0.11300781 0.97774895 0.21734292]]


Array2:
[[0.35819445 0.86215122 0.49733072]
 [0.54508252 0.57595009 0.23447591]
 [0.60362165 0.36569244 0.20179221]]


Equality: False
